### ISSUE TITLE
I'm curious about the CBUS pins possibilities.

### ISSUE THREAD

**Issue by madeintheusb** [DeuxVis/FT231X_breakout#1]
The FT231X and the FT232R as well a have very interesting and not well documented named Synchronous bit banging. CBUS will always be limited to 4 IO.
See my device www.Nusbio.net. At some point I used an FT231X but came back to the FT232RL because I do not want to do the reflow  myself.

**Comment by DeuxVis** [comment]
Well theoretically - I didn't test that yet - you could expand that to 8 IO with some simple glue logic : using 3 bits for address and 1 for data.

To be honest I only used FT231X because that's what I had in stock, and being limited to 4 bits was not a problem for my application.
